<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;

class GuiaInventario extends Model
{
    use HasFactory;

    protected $table = 'guias_inventario';

    protected $fillable = [
        'tipo_movimiento',
        'proveedor_id',
        'sede_origen_id',
        'almacen_origen_id',
        'sede_destino_id',
        'almacen_destino_id',
        'tipo_documento_id',
        'serie',
        'correlativo',
        'fecha_movimiento',
        'estado',
        'motivo',
        'venta_id',
        'creado_por_usuario_id',
    ];

    protected $casts = [
        'fecha_movimiento' => 'date',
        'correlativo' => 'integer',
    ];

    /**
     * Get the provider of the inventory guide (if Entry).
     *
     * @return BelongsTo<Proveedor, $this>
     */
    public function proveedor(): BelongsTo
    {
        return $this->belongsTo(Proveedor::class);
    }

    /**
     * Get the origin warehouse.
     *
     * @return BelongsTo<Almacen, $this>
     */
    public function almacenOrigen(): BelongsTo
    {
        return $this->belongsTo(Almacen::class, 'almacen_origen_id');
    }

    /**
     * Get the destination warehouse.
     *
     * @return BelongsTo<Almacen, $this>
     */
    public function almacenDestino(): BelongsTo
    {
        return $this->belongsTo(Almacen::class, 'almacen_destino_id');
    }

    /**
     * Get the document type.
     *
     * @return BelongsTo<TipoDocumento, $this>
     */
    public function tipoDocumento(): BelongsTo
    {
        return $this->belongsTo(TipoDocumento::class);
    }

    /**
     * Get the user who created this guide.
     *
     * @return BelongsTo<User, $this>
     */
    public function creador(): BelongsTo
    {
        return $this->belongsTo(User::class, 'creado_por_usuario_id');
    }

    /**
     * Get the details for this inventory guide.
     *
     * @return HasMany<GuiaInventarioDetalle, $this>
     */
    public function detalles(): HasMany
    {
        return $this->hasMany(GuiaInventarioDetalle::class, 'guia_inventario_id');
    }

    /**
     * Get the Kardex records generated by this guide.
     *
     * @return MorphMany<Kardex, $this>
     */
    public function movimientosKardex(): MorphMany
    {
        return $this->morphMany(Kardex::class, 'origen_documento');
    }
}
