<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class GuiaInventario extends Model
{
    use HasFactory, \Illuminate\Database\Eloquent\SoftDeletes;

    protected $table = 'guias_inventario';

    protected $fillable = [
        'tipo_movimiento',
        'proveedor_id',
        'sede_origen_id',
        'almacen_origen_id',
        'sede_destino_id',
        'almacen_destino_id',
        'tipo_documento_id',
        'serie',
        'correlativo',
        'fecha_movimiento',
        'estado',
        'motivo',
        'venta_id',
        'created_by',
        'updated_by',
        'deleted_by',
    ];

    protected $casts = [
        'fecha_movimiento' => 'date',
        'correlativo' => 'integer',
    ];

    protected static function booted()
    {
        static::creating(function ($model) {
            $model->created_by = auth()->id();
            $model->updated_by = auth()->id();
        });

        static::updating(function ($model) {
            $model->updated_by = auth()->id();
        });

        static::deleting(function ($model) {
            if (in_array(SoftDeletes::class, class_uses_recursive($model))) {
                if (! $model->isForceDeleting()) {
                    $model->deleted_by = auth()->id();
                    $model->saveQuietly();
                }
            }
        });
    }

    /**
     * Get the provider of the inventory guide (if Entry).
     *
     * @return BelongsTo<Proveedor, $this>
     */
    public function proveedor(): BelongsTo
    {
        return $this->belongsTo(Proveedor::class);
    }

    /**
     * Get the origin warehouse.
     *
     * @return BelongsTo<Almacen, $this>
     */
    public function almacenOrigen(): BelongsTo
    {
        return $this->belongsTo(Almacen::class, 'almacen_origen_id');
    }

    /**
     * Get the destination warehouse.
     *
     * @return BelongsTo<Almacen, $this>
     */
    public function almacenDestino(): BelongsTo
    {
        return $this->belongsTo(Almacen::class, 'almacen_destino_id');
    }

    /**
     * Get the document type.
     *
     * @return BelongsTo<TipoDocumento, $this>
     */
    public function tipoDocumento(): BelongsTo
    {
        return $this->belongsTo(TipoDocumento::class);
    }

    /**
     * Get the user who created this guide.
     *
     * @return BelongsTo<User, $this>
     */
    public function creador(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * Get the details for this inventory guide.
     *
     * @return HasMany<GuiaInventarioDetalle, $this>
     */
    public function detalles(): HasMany
    {
        return $this->hasMany(GuiaInventarioDetalle::class, 'guia_inventario_id');
    }

    /**
     * Get the Kardex records generated by this guide.
     *
     * @return MorphMany<Kardex, $this>
     */
    public function movimientosKardex(): MorphMany
    {
        return $this->morphMany(Kardex::class, 'origen_documento');
    }
}
