<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;

class Venta extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'tipo_documento_id',
        'serie',
        'correlativo',
        'estado_pago',
        'estado_despacho',
        'subtotal',
        'descuento',
        'costo_envio',
        'total',
        'tipo_pago',
        'metodo_pago',
        'cupon_id',
        'direccion_id',
        'envio_destinatario',
        'envio_telefono',
        'envio_direccion',
        'envio_referencia',
        'envio_distrito',
        'envio_provincia',
        'envio_departamento',
        'comentarios',
    ];

    protected $casts = [
        'correlativo' => 'integer',
        'subtotal' => 'decimal:2',
        'descuento' => 'decimal:2',
        'costo_envio' => 'decimal:2',
        'total' => 'decimal:2',
    ];

    /**
     * Get the customer (user) who bought the sale.
     *
     * @return BelongsTo<User, $this>
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Dirección de envío referenciada al crear la venta.
     *
     * @return BelongsTo<Direccion, $this>
     */
    public function direccionEnvio(): BelongsTo
    {
        return $this->belongsTo(Direccion::class, 'direccion_id');
    }

    /**
     * Get the document type.
     *
     * @return BelongsTo<TipoDocumento, $this>
     */
    public function tipoDocumento(): BelongsTo
    {
        return $this->belongsTo(TipoDocumento::class);
    }

    /**
     * Get the coupon applied.
     *
     * @return BelongsTo<Cupon, $this>
     */
    public function cupon(): BelongsTo
    {
        return $this->belongsTo(Cupon::class);
    }

    /**
     * Get the items (details) for this sale.
     *
     * @return HasMany<VentaDetalle, $this>
     */
    public function detalles(): HasMany
    {
        return $this->hasMany(VentaDetalle::class);
    }

    /**
     * Get the Kardex records generated by this sale.
     *
     * @return MorphMany<Kardex, $this>
     */
    public function movimientosKardex(): MorphMany
    {
        return $this->morphMany(Kardex::class, 'origen_documento');
    }
}
